### ISSUE TITLE
Great plugins - can we add more features

### ISSUE THREAD

**Issue by kassio** [emmanueltouzery/agitator.nvim#3]
Thanks for the work on this one!!

Do you think in add more features, like fugitive.vim? The ones I missed most:

1. More information on the blame window
2. Open the commit on current line on a horizontal window (with 'o')

**Comment by emmanueltouzery** [comment]
This second feature I actually implemented for myself in my dotfiles. But it depends on the external diffview plugin to display the commit. That's why I didn't put it here. But maybe I can do something about it still.

The blame window, what else would you add? I combine this with the gitsigns popup to view message etc, I think that wouldn't fit in the sidebar?

**Comment by kassio** [comment]
> The blame window, what else would you add? I combine this with the gitsigns popup to view message etc, I think that wouldn't fit in the sidebar?

Maybe one option to get the commit first line (title). It's been a while since I used fugitive, but I think it has something like that.

(and thanks again for being so proactive, I really appreciate it)

**Comment by emmanueltouzery** [comment]
Yes, about your second idea, I knew I have this in my dotfiles, this is how I do it:

```lua
function _G.ShowCommitAtLine()
    local commit_sha = require"agitator".git_blame_commit_for_line()
    vim.cmd("DiffviewOpen " .. commit_sha .. "^.." .. commit_sha)
end
```

So you can use `git_blame_commit_for_line()` to get the commit SHA, then use your favorite plugin to display that commit. Here I used diffview, but I'm pretty sure it's possible with neogit or something else, even fugitive.

I'll do something about your second idea, but a bit later (in fact I'm working on adding another feature to agitator right now).

**Comment by kassio** [comment]
@emmanueltouzery, thanks for that. On `vim.cmd("DiffviewOpen " .. commit_sha .. "^.." .. commit_sha)`, how did you define `DiffviewOpen`?

**Comment by emmanueltouzery** [comment]
it comes from https://github.com/sindrets/diffview.nvim/
options would be at least diffview or neogit libraries. I don't plan on having a way to display commits from within agitator.nvim

**Comment by emmanueltouzery** [comment]
I pushed a commit implementing the first feature you were requesting, see the updated readme. Basically you can now give a lua function specifying how you would format the blame info. And since it's parameter of the call, not config, you could have two shortcuts, one showing the summary, one the author, if you wanted, for instance.
